### ISSUE TITLE
Post timestamp

### ISSUE THREAD

**Issue by mrgnschndr** [cacheUsIfYouCan/insta-clone#11]
#Feature Request

**Name:** Post timestamp

**Description:** This feature displays the time at which the post was uploaded. The time format changes dynamically dependent on how much time has elapsed since the upload.

**Requirements/Acceptance Criteria:**
- [x] Under each post and caption, the timestamp for the post will be displayed in grey text and left aligned.
- [x] The format of the time will follow the rules below:
     - [x] 0 sec to 59 seconds: "X second(s) ago"
     - [x] 1 min to 59 minutes: "X minute(s) ago"
     - [x] 1 hour to 23 hours: "X hour(s) ago"
     - [x] 24 hours to 48 hours: "1 day ago"
     - [x] 49 hours to 6 days: "X days ago"
     - [x] > 7 days and year is current year: "Month Day" (e.g. November 19, April 4)
     - [x] > 7 days and year is previous year: Full Date (e.g. May 7, 2023)

**Mockup/Design:**
![Image](https://github.com/user-attachments/assets/e6b9a77a-db33-4cf8-923e-bf077f5e994d)
![Image](https://github.com/user-attachments/assets/38a7b8c3-ae84-48e9-ad71-39a197a3b36b)
![Image](https://github.com/user-attachments/assets/924769a9-85f8-49f8-ac03-3c42b7423406)

**Dependencies:**

**Comment by krissyjames** [comment]
Since I need to make sure all of the JSON is added into app.js, I will do that here
